- { players:  5, breakdown: { townsfolk: 3, outsider: 0, minion: 1, demon: 1 } }
- { players:  6, breakdown: { townsfolk: 3, outsider: 1, minion: 1, demon: 1 } }
- { players:  7, breakdown: { townsfolk: 5, outsider: 0, minion: 1, demon: 1 } }
- { players:  8, breakdown: { townsfolk: 5, outsider: 1, minion: 1, demon: 1 } }
- { players:  9, breakdown: { townsfolk: 5, outsider: 2, minion: 1, demon: 1 } }
- { players: 10, breakdown: { townsfolk: 7, outsider: 0, minion: 2, demon: 1 } }
- { players: 11, breakdown: { townsfolk: 7, outsider: 1, minion: 2, demon: 1 } }
- { players: 12, breakdown: { townsfolk: 7, outsider: 2, minion: 2, demon: 1 } }
- { players: 13, breakdown: { townsfolk: 9, outsider: 0, minion: 3, demon: 1 } }
- { players: 14, breakdown: { townsfolk: 9, outsider: 1, minion: 3, demon: 1 } }
- { players: 15, breakdown: { townsfolk: 9, outsider: 2, minion: 3, demon: 1 } }
